#!/bin/sh

# This is the example configuration file for river.
#
# If you wish to edit this, you will probably want to copy it to
# $XDG_CONFIG_HOME/river/init or $HOME/.config/river/init first.
#
# See the river(1), ~/.local/bin/riverctl(1), and ~/.local/bin/rivertile(1) man pages for complete
# documentation.

# Note: the "Super" modifier is also known as Logo, GUI, Windows, Mod4, etc.

# Super+Shift+Return to start an instance of foot (https://codeberg.org/dnkl/foot)
~/.local/bin/riverctl map normal Super+Shift Return spawn alacritty
~/.local/bin/riverctl map normal Super Return spawn alacritty
~/.local/bin/riverctl map normal Super+Shift Space spawn "wofi -S drun -I -L 12"

# Super+Q to close the focused view
~/.local/bin/riverctl map normal Super Q close

# Super+Shift+E to exit river
~/.local/bin/riverctl map normal Super+Shift E exit

# Super+J and Super+K to focus the next/previous view in the layout stack
~/.local/bin/riverctl map normal Super J focus-view next
~/.local/bin/riverctl map normal Super K focus-view previous

# Super+Shift+J and Super+Shift+K to swap the focused view with the next/previous
# view in the layout stack
~/.local/bin/riverctl map normal Super+Shift J swap next
~/.local/bin/riverctl map normal Super+Shift K swap previous

# Super+Period and Super+Comma to focus the next/previous output
~/.local/bin/riverctl map normal Super Period focus-output next
~/.local/bin/riverctl map normal Super Comma focus-output previous

# Super+Shift+{Period,Comma} to send the focused view to the next/previous output
~/.local/bin/riverctl map normal Super+Shift Period send-to-output next
~/.local/bin/riverctl map normal Super+Shift Comma send-to-output previous

# Super+Return to bump the focused view to the top of the layout stack
~/.local/bin/riverctl map normal Super Return zoom

# Super+H and Super+L to decrease/increase the main ratio of ~/.local/bin/rivertile(1)
~/.local/bin/riverctl map normal Super H send-layout-cmd ~/.local/bin/rivertile "main-ratio -0.05"
~/.local/bin/riverctl map normal Super L send-layout-cmd ~/.local/bin/rivertile "main-ratio +0.05"

# Super+Shift+H and Super+Shift+L to increment/decrement the main count of ~/.local/bin/rivertile(1)
~/.local/bin/riverctl map normal Super+Shift H send-layout-cmd ~/.local/bin/rivertile "main-count +1"
~/.local/bin/riverctl map normal Super+Shift L send-layout-cmd ~/.local/bin/rivertile "main-count -1"

# Super+Alt+{H,J,K,L} to move views
~/.local/bin/riverctl map normal Super+Alt H move left 100
~/.local/bin/riverctl map normal Super+Alt J move down 100
~/.local/bin/riverctl map normal Super+Alt K move up 100
~/.local/bin/riverctl map normal Super+Alt L move right 100

# Super+Alt+Control+{H,J,K,L} to snap views to screen edges
~/.local/bin/riverctl map normal Super+Alt+Control H snap left
~/.local/bin/riverctl map normal Super+Alt+Control J snap down
~/.local/bin/riverctl map normal Super+Alt+Control K snap up
~/.local/bin/riverctl map normal Super+Alt+Control L snap right

# Super+Alt+Shift+{H,J,K,L} to resize views
~/.local/bin/riverctl map normal Super+Alt+Shift H resize horizontal -100
~/.local/bin/riverctl map normal Super+Alt+Shift J resize vertical 100
~/.local/bin/riverctl map normal Super+Alt+Shift K resize vertical -100
~/.local/bin/riverctl map normal Super+Alt+Shift L resize horizontal 100

# Super + Left Mouse Button to move views
~/.local/bin/riverctl map-pointer normal Super BTN_LEFT move-view

# Super + Right Mouse Button to resize views
~/.local/bin/riverctl map-pointer normal Super BTN_RIGHT resize-view

# Super + Middle Mouse Button to toggle float
~/.local/bin/riverctl map-pointer normal Super BTN_MIDDLE toggle-float

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    ~/.local/bin/riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    ~/.local/bin/riverctl map normal Super+Shift $i set-view-tags $tags

    # Super+Control+[1-9] to toggle focus of tag [0-8]
    ~/.local/bin/riverctl map normal Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Control+[1-9] to toggle tag [0-8] of focused view
    ~/.local/bin/riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
~/.local/bin/riverctl map normal Super 0 set-focused-tags $all_tags
~/.local/bin/riverctl map normal Super+Shift 0 set-view-tags $all_tags

# Super+Space to toggle float
~/.local/bin/riverctl map normal Super T toggle-float

# Super+F to toggle fullscreen
~/.local/bin/riverctl map normal Super F toggle-fullscreen

# Super+{Up,Right,Down,Left} to change layout orientation
~/.local/bin/riverctl map normal Super Up    send-layout-cmd ~/.local/bin/rivertile "main-location top"
~/.local/bin/riverctl map normal Super Right send-layout-cmd ~/.local/bin/rivertile "main-location right"
~/.local/bin/riverctl map normal Super Down  send-layout-cmd ~/.local/bin/rivertile "main-location bottom"
~/.local/bin/riverctl map normal Super Left  send-layout-cmd ~/.local/bin/rivertile "main-location left"

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
~/.local/bin/riverctl declare-mode passthrough

# Super+F11 to enter passthrough mode
~/.local/bin/riverctl map normal Super F11 enter-mode passthrough

# Super+F11 to return to normal mode
~/.local/bin/riverctl map passthrough Super F11 enter-mode normal

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do
    # Eject the optical drive (well if you still have one that is)
    ~/.local/bin/riverctl map $mode None XF86Eject spawn 'eject -T'

    # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
    ~/.local/bin/riverctl map $mode None XF86AudioRaiseVolume  spawn 'pamixer -i 5'
    ~/.local/bin/riverctl map $mode None XF86AudioLowerVolume  spawn 'pamixer -d 5'
    ~/.local/bin/riverctl map $mode None XF86AudioMute         spawn 'pamixer --toggle-mute'

    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    ~/.local/bin/riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    ~/.local/bin/riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    ~/.local/bin/riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
    ~/.local/bin/riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

    # Control screen backlight brightness with brightnessctl (https://github.com/Hummer12007/brightnessctl)
    ~/.local/bin/riverctl map $mode None XF86MonBrightnessUp   spawn 'brightnessctl set +5%'
    ~/.local/bin/riverctl map $mode None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'
done

# Set background and border color
~/.local/bin/riverctl background-color 0x002b36
~/.local/bin/riverctl border-color-focused 0x93a1a1
~/.local/bin/riverctl border-color-unfocused 0x586e75

# Set keyboard repeat rate
~/.local/bin/riverctl set-repeat 50 300

# Make all views with an app-id that starts with "float" and title "foo" start floating.
~/.local/bin/riverctl rule-add -app-id 'float*' -title 'foo' float

# Make all views with app-id "bar" and any title use client-side decorations
~/.local/bin/riverctl rule-add -app-id "bar" csd

# Set the default layout generator to be ~/.local/bin/rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
~/.local/bin/riverctl default-layout ~/.local/bin/rivertile
~/.local/bin/rivertile -view-padding 6 -outer-padding 6 &
